version: '3.1'
services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: todolist
      MARIADB_USER: todolist
      MARIADB_PASSWORD: todolistpass
    ports:
      - 3308:3306
    expose:
      - 3306
    volumes:
      - ./api/db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  backend:
    image: node:20-alpine
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    command: sh -c "cd ./api/ && yarn install  && yarn start"
    ports:
      - 3000:3000
    depends_on:
      - db
  
  frontend:
    image: node:20-alpine
    restart: always
    working_dir: /usr/src/front
    volumes:
      - ./frontend:/usr/src/front
    command: sh -c "cd ../front && yarn install && yarn build && cd dist && npx http-server -p 3001"
    ports:
      - 3001:3001
